# Generated by Django 4.1.1 on 2022-10-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_diagnose_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnose',
            name='user',
        ),
    ]
